services:
  gluetun:
        image: qmcgaw/gluetun
        container_name: gluetun
        cap_add:
            - NET_ADMIN
        devices:
            - /dev/net/tun:/dev/net/tun
        environment:
            - VPN_SERVICE_PROVIDER=nordvpn
            - VPN_TYPE=openvpn # or wireguard
            - OPENVPN_USER=ANjcTRAkd2sx5tRbssYzFcuH
            - OPENVPN_PASSWORD=QhTZa4VLtswTHNb262GD93ie
            - SERVER_COUNTRIES=Netherlands
        ports:
            - 8001:8000/tcp

  transmission-openvpn:
        container_name: transmission
        cap_add:
            - NET_ADMIN
        volumes:
            - ${DOWNLOADS}/Torrents:/data
            - ${APPDATA}/transmission:/config
        environment:
            - CREATE_TUN_DEVICE=true
            - DROP_DEFAULT_ROUTE=
            - ENABLE_UFW=false
            - GLOBAL_APPLY_PERMISSIONS=true
            - HEALTH_CHECK_HOST=google.com
            - LOCAL_NETWORK=10.0.0.0/16
            - LOG_TO_STDOUT=false
            - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
            - OPENVPN_PASSWORD=QhTZa4VLtswTHNb262GD93ie
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_USERNAME=ANjcTRAkd2sx5tRbssYzFcuH
            - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            - PEER_DNS=true
            - PEER_DNS_PIN_ROUTES=true
            - PGID=${PGID}
            - PUID=${PUID}
            - REVISION=07f5a2b9aea5028c9bb75438c1552708e91dde71
            - SELFHEAL=false
            - TRANSMISSION_DOWNLOAD_DIR=/data/completed
            - TRANSMISSION_DOWNLOAD_LIMIT=5000
            - TRANSMISSION_DOWNLOAD_LIMIT_ENABLED=1
            - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=10
            - TRANSMISSION_HOME=/config/transmission-home
            - TRANSMISSION_IDLE_SEEDING_LIMIT=10
            - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=true
            - TRANSMISSION_INCOMPLETE_DIR=/data/incomplete
            - TRANSMISSION_QUEUE_STALLED_MINUTES=10
            - TRANSMISSION_RATIO_LIMIT=1
            - TRANSMISSION_RATIO_LIMIT_ENABLED=true
            - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
            - TRANSMISSION_RPC_PASSWORD=7508216
            - TRANSMISSION_RPC_PORT=9091
            - TRANSMISSION_RPC_USERNAME=racemiller
            - TRANSMISSION_WATCH_DIR=/data/watch
            - TRANSMISSION_WEB_UI=flood-for-transmission
            - TZ=${TZ}
            - UFW_ALLOW_GW_NET=false
            - UFW_DISABLE_IPTABLES_REJECT=false
            - UFW_EXTRA_PORTS=
            - WEBPROXY_ENABLED=false
            - WEBPROXY_PASSWORD=
            - WEBPROXY_PORT=8118
            - WEBPROXY_USERNAME=
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - 9091:9091
        image: haugene/transmission-openvpn
        restart: unless-stopped

  jdownloader-2:
    image: jlesage/jdownloader-2
    container_name: jdownloader
    ports:
      - 5800:5800
      - 3129:3129
    volumes:
      - ${APPDATA}/jdownloader:/config:rw
      - ${DOWNLOADS}/Jdownloader:/output:rw
    restart: unless-stopped

  gpodder:
    image: xthursdayx/gpodder-docker
    container_name: gpodder
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD= #optional
    volumes:
      - ${APPDATA}/gpodder:/config
      - ${DOWNLOADS}/Podcasts:/downloads
    ports:
      - 3000:3000
    restart: unless-stopped
    
  podfetch:
    image: samuel19982/podfetch:latest
    container_name: podfetch
    user: ${PUID}:${PGID}
    ports:
      - 8005:8000
    volumes:
      - ${DOWNLOADS}/Podcasts:/app/podcasts
      - ${APPDATA}/podfetch:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:8005
      - DATABASE_URL=sqlite:///app/db/podcast.db

  resilio-sync:
    image: lscr.io/linuxserver/resilio-sync:latest
    container_name: resilio-sync
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/resilio:/config
      - ${DOWNLOADS}/Torrents/completed:/downloads
      - ${DATA}/Fan Edits:/sync
    ports:
      - 8889:8888
      - 55555:55555
    restart: unless-stopped

  slskd:
    image: slskd/slskd
    container_name: slskd
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    environment:
      - SLSKD_REMOTE_CONFIGURATION=true
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${APPDATA}/slskd:/app
      - ${DOWNLOADS}/Soulseek:/app/downloads
      - ${DATA}/Music/Regular Music:/music
    restart: unless-stopped

  tubearchivist:
    container_name: tubearchivist
    restart: unless-stopped
    image: bbilly1/tubearchivist
    network_mode: service:gluetun
#    ports:
#      - 8001:8000
    volumes:
      - ${DATA}/YouTube:/youtube
      - ${APPDATA}/tubearchivist:/cache
    environment:
      - ES_URL=http://archivist-es:9200   # needs protocol e.g. http and port # needs to reference the IP of the archivist-es container
      - REDIS_CON=redis://archivist-redis:6379
      - HOST_UID=${PUID}
      - HOST_GID=${PGID}
      - TA_HOST=http://10.0.0.2/24 https://tube.racemiller.com         # set your host name
      - TA_USERNAME=racemiller           # your initial TA credentials
      - TA_PASSWORD=7508216              # your initial TA credentials
      - ELASTIC_PASSWORD=7508216         # set password for Elasticsearch
      - TZ=${TZ}                 # set your time zone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health"]
      interval: 2m
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - archivist-es
      - archivist-redis
  archivist-redis:
    image: redis
    container_name: archivist-redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ${APPDATA}/tubearchivist/redis:/data
    depends_on:
      - archivist-es
  archivist-es:
    image: bbilly1/tubearchivist-es         # only for amd64, or use official es 8.16.0
    container_name: archivist-es
    restart: unless-stopped
    hostname: archivist-es
#    networks:
#     default:
#        ipv4_address: 192.168.128.2
    environment:
      - "ELASTIC_PASSWORD=7508216"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

# Not using this for now because it has issues

# sonarr_youtubedl:
#   image: sonarr-ytdlp:latest
#   container_name: sonarr-ytdl
#   environment:
#     - TZ=${TZ}
#     - PUID=${PUID}
#     - PGID=${PGID}
#   labels:
#     - com.centurylinklabs.watchtower.enable=false
#   volumes:
#     - ${APPDATA}/sonarr-youtubedl:/config
#     - ${DATA}:/sonarr_root
#     - ${APPDATA}/sonarr-youtubedl/logs:/logs
#   restart: unless-stopped

  soularr:
    image: mrusse08/soularr:latest
    container_name: soularr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SCRIPT_INTERVAL=3600
    user: ${PUID}:${PGID}
    volumes:
      - ${DOWNLOADS}/Soulseek:/downloads
      - ${APPDATA}/soularr:/data
    restart: unless-stopped

  xmas-soularr:
    image: mrusse08/soularr:latest
    container_name: xmas-soularr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SCRIPT_INTERVAL=86400
    user: ${PUID}:${PGID}
    volumes:
      - ${DOWNLOADS}/Soulseek:/downloads
      - ${APPDATA}/xmas-soularr:/data
    restart: unless-stopped
    
volumes:
  es:

networks:
  default:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.128.0/20
         gateway: 192.168.128.1
